import { MissionDefinition } from '@missionx/shared';

export const THE_LOST_SENSOR_NETWORK_DEFINITION: MissionDefinition = {
  id: 'mission-sensor-network-03',
  slug: 'lost-sensor-network',
  title: 'The Lost Sensor Network',
  domain: 'Networking / IoT',
  difficulty: 'Medium',
  description:
    'Multiple remote IoT sensor nodes in the facility automation network have abruptly ceased transmitting telemetry to the central gateway. Analyze network topology, isolate the disconnected node, diagnose switch port dropouts, select a resilient routing path, and restore bidirectional telemetry to re-open the network operations center exit.',
  briefing:
    'Several IoT sensor nodes have stopped communicating with the central gateway. Identify the disconnected node, analyze the network information, and restore the communication route.',
  estimatedDuration: '12–15 min',
  learningObjectives: [
    'Analyze IoT mesh and star network topologies',
    'Diagnose packet loss and port-link failures',
    'Trace routing hops across network switches and wireless APs',
    'Configure gateway routing tables and security clearance keys',
    'Verify restored bidirectional telemetry streams',
  ],
  version: 1,
  settings: {
    allowHints: true,
    maxAttempts: 5,
    passScorePercentage: 70,
  },
  stages: [
    {
      id: 'stage-1',
      order: 1,
      title: 'Inspect Sensor Nodes',
      objective: 'Inspect the network monitoring screen and isolate the unresponsive sensor node.',
      description:
        'The gateway reports heartbeat packet dropouts. Inspect node status indicators on the central monitoring screen to identify which node is unreachable.',
      interactionIds: [
        'inspect-monitoring-screen',
        'inspect-sensor-nodes',
        'q1-offline-node-interaction',
      ],
      questionIds: ['q1_offline_node'],
      hintIds: ['hint-network-stage-1'],
      rewardIds: ['reward-network-stage-1-xp', 'reward-network-stage-1-score'],
    },
    {
      id: 'stage-2',
      order: 2,
      title: 'Diagnose Network Infrastructure',
      objective: 'Examine the managed switch and router to pinpoint the layer-1/2 link failure.',
      description:
        'Access the managed network switch console and inspect link status, MAC address tables, and port transmission errors to discover why Node C is isolated.',
      interactionIds: [
        'inspect-network-switch',
        'inspect-router',
        'q2-network-fault-interaction',
      ],
      questionIds: ['q2_network_fault'],
      hintIds: ['hint-network-stage-2'],
      rewardIds: ['reward-network-stage-2-xp', 'reward-network-stage-2-score'],
    },
    {
      id: 'stage-3',
      order: 3,
      title: 'Select Resilient Route',
      objective: 'Determine the alternate wireless routing hops to bypass the severed physical cable.',
      description:
        'With Ethernet Port 3 down, select an alternate wireless mesh route via the industrial access point to bridge Node C back to the central gateway.',
      interactionIds: [
        'inspect-wireless-ap',
        'inspect-packet-console',
        'q3-route-selection-interaction',
      ],
      questionIds: ['q3_route_selection'],
      hintIds: ['hint-network-stage-3'],
      rewardIds: [
        'reward-network-stage-3-xp',
        'reward-stage-3-score',
        'reward-network-stage-3-clue-key',
      ],
    },
    {
      id: 'stage-4',
      order: 4,
      title: 'Restore Gateway Link',
      objective: 'Authenticate the gateway route update code to latch the network routing table and unlock the NOC exit.',
      description:
        'Enter the routing authentication authorization key into the central gateway terminal to verify 100% packet delivery across all nodes and unlock the exit.',
      interactionIds: [
        'inspect-central-gateway',
        'q4-restore-node-interaction',
      ],
      questionIds: ['q4_restore_node'],
      hintIds: ['hint-network-stage-4'],
      rewardIds: [
        'reward-network-stage-4-xp',
        'reward-network-stage-4-score',
        'reward-network-stage-4-badge-repairer',
      ],
      isFinalStage: true,
    },
  ],
  interactions: [
    {
      id: 'inspect-monitoring-screen',
      type: 'INSPECT',
      targetObjectId: 'monitoring_screen',
      stageId: 'stage-1',
      title: 'Inspect Central Telemetry Screen',
      description: 'Review the live node telemetry dashboard.',
      feedbackMessage: 'Dashboard Telemetry: Node A (ONLINE | 24ms), Node B (ONLINE | 18ms), Node C (OFFLINE | 100% Packet Loss), Node D (ONLINE | 21ms).',
      config: {
        monitorType: 'Wall-Mounted NOC Telemetry Display',
        nodeA: 'ONLINE (192.168.1.51)',
        nodeB: 'ONLINE (192.168.1.52)',
        nodeC: 'OFFLINE / UNREACHABLE (192.168.1.53)',
        nodeD: 'ONLINE (192.168.1.54)',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'inspect-sensor-nodes',
      type: 'INSPECT',
      targetObjectId: 'sensor_nodes',
      stageId: 'stage-1',
      title: 'Inspect Field Sensor Node Array',
      description: 'Check physical status LEDs on the bench-mounted sensor nodes.',
      feedbackMessage: 'Node C LED is blinking fast Amber (Error: No Link Carrier). Nodes A, B, D show solid Green.',
      config: {
        nodeType: 'ESP32 Industrial IoT Node Clusters',
        faultNode: 'Node C (Module #3)',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q1-offline-node-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'monitoring_screen',
      stageId: 'stage-1',
      title: 'Identify Disconnected Node',
      questionId: 'q1_offline_node',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Fault isolated: Node C confirmed disconnected.',
    },
    {
      id: 'inspect-network-switch',
      type: 'INSPECT',
      targetObjectId: 'network_switch',
      stageId: 'stage-2',
      title: 'Inspect Managed Switch Diagnostics',
      description: 'Examine port activity lights on the 24-Port Gigabit switch.',
      feedbackMessage: 'Port 3 Link Light is UNLIT (Physical Link Down). Port error counter: 24 CRC Errors, Carrier Lost.',
      config: {
        hardware: 'Managed L2+ 24-Port Gigabit Switch',
        port1: 'UP (Gateway Uplink)',
        port2: 'UP (Node A & B)',
        port3: 'DOWN (Node C Cable Fault)',
        port4: 'UP (Wireless AP)',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'inspect-router',
      type: 'INSPECT',
      targetObjectId: 'router',
      stageId: 'stage-2',
      title: 'Inspect Core Gateway Router',
      description: 'Review router IP routing table and gateway interfaces.',
      feedbackMessage: 'Core Router (192.168.1.1) is ONLINE. ARP table entry for Node C is stale (INCOMPLETE).',
      config: {
        device: 'Industrial Edge Router',
        status: 'ONLINE',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q2-network-fault-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'network_switch',
      stageId: 'stage-2',
      title: 'Submit Network Diagnostic',
      questionId: 'q2_network_fault',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Diagnostic verified: Switch Port 3 cable severed. Physical layer link down.',
    },
    {
      id: 'inspect-wireless-ap',
      type: 'INSPECT',
      targetObjectId: 'wireless_ap',
      stageId: 'stage-3',
      title: 'Inspect Industrial Wireless Access Point',
      description: 'Check WiFi 6 / 802.11ax IoT bridge transceiver status.',
      feedbackMessage: 'AP SSID "MISSIONX-MESH" active on 2.4 GHz. Node C wireless radio detected with -58 dBm RSSI.',
      config: {
        device: 'Dual-Band Industrial AP',
        meshSSID: 'MISSIONX-MESH',
        signalQuality: '-58 dBm (Strong)',
        encryption: 'WPA3-Enterprise',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'inspect-packet-console',
      type: 'INSPECT',
      targetObjectId: 'packet_console',
      stageId: 'stage-3',
      title: 'Inspect Packet Routing Console',
      description: 'Interactive route selection terminal.',
      feedbackMessage: 'Select route to establish wireless bridge from Node C through the Wireless AP into the Central Gateway.',
      config: {
        terminal: 'Dynamic Routing Configuration Engine',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q3-route-selection-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'packet_console',
      stageId: 'stage-3',
      title: 'Select Bypass Route',
      questionId: 'q3_route_selection',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Route topology selected! Node C packets successfully rerouted via Wireless AP.',
    },
    {
      id: 'inspect-central-gateway',
      type: 'INSPECT',
      targetObjectId: 'central_gateway',
      stageId: 'stage-4',
      title: 'Inspect Central IoT Gateway',
      description: 'Master MQTT / CoAP telemetry aggregation hub.',
      feedbackMessage: 'Gateway awaiting route latch confirmation. Input route authentication key to permanently bind mesh route.',
      config: {
        hubType: 'Carrier IoT Gateway Hub',
        protocol: 'MQTT Broker Port 1883',
        status: 'LATCH_READY',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q4-restore-node-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'central_gateway',
      stageId: 'stage-4',
      title: 'Authorize Route Table Latch',
      questionId: 'q4_restore_node',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Authentication accepted! All 4 sensor nodes ONLINE. NOC exit door disengaged.',
    },
  ],
  questions: [
    {
      id: 'q1_offline_node',
      prompt: 'Reviewing the NOC telemetry monitoring dashboard, which IoT sensor node is currently failing to communicate?',
      type: 'multiple_choice',
      options: ['Node A', 'Node B', 'Node C', 'Node D'],
      correctAnswer: 'Node C',
      explanation: 'The monitoring screen clearly flags Node C as OFFLINE with 100% packet loss and an unlit heartbeat indicator.',
      points: 100,
      maxAttempts: 3,
      stageId: 'stage-1',
      learningObjective: 'Analyze IoT mesh and star network topologies',
    },
    {
      id: 'q2_network_fault',
      prompt: 'What is the primary physical/data link layer fault causing Node C to become unreachable from the switch?',
      type: 'multiple_choice',
      options: [
        'Port 3 link failure / disconnected cable route',
        'Gateway DNS lookup timeout',
        'IP address collision with Node A',
        'WiFi encryption key mismatch',
      ],
      correctAnswer: 'Port 3 link failure / disconnected cable route',
      explanation:
        'Switch inspection shows Port 3 is physically DOWN with carrier lost, indicating an unplugged or severed Ethernet run.',
      points: 100,
      maxAttempts: 3,
      stageId: 'stage-2',
      learningObjective: 'Diagnose packet loss and port-link failures',
    },
    {
      id: 'q3_route_selection',
      prompt: 'To bypass the damaged Ethernet run and re-establish telemetry flow from Node C into the Central Gateway, select the correct network hops:',
      type: 'multiple_choice',
      options: [
        'Sensor Node C → Wireless AP → Network Switch → Central Gateway',
        'Sensor Node C → Direct Internet → Gateway WAN',
        'Sensor Node C → Sensor Node A → Sensor Node B → Internet',
        'Network Switch → Node C → Router → Gateway',
      ],
      correctAnswer: 'Sensor Node C → Wireless AP → Network Switch → Central Gateway',
      explanation:
        'Connecting Node C via the nearby Wireless AP routes wireless frames back to the managed switch (Port 4), cleanly delivering packets to the Central Gateway.',
      points: 100,
      maxAttempts: 3,
      stageId: 'stage-3',
      learningObjective: 'Trace routing hops across network switches and wireless APs',
    },
    {
      id: 'q4_restore_node',
      prompt: 'Enter the 5-character Gateway Routing Authorization Code revealed upon establishing the wireless bridge:',
      type: 'code',
      correctAnswer: 'NET99',
      explanation: 'Code NET99 commits the static routing entry and synchronizes the MQTT broker.',
      points: 200,
      maxAttempts: 5,
      stageId: 'stage-4',
      learningObjective: 'Configure gateway routing tables and security clearance keys',
    },
  ],
  hints: [
    {
      id: 'hint-network-stage-1',
      stageId: 'stage-1',
      text: 'Look at the monitoring screen: Node A, B, and D are marked ONLINE in green, but Node C is marked OFFLINE in red.',
      penalty: 15,
      order: 1,
    },
    {
      id: 'hint-network-stage-2',
      stageId: 'stage-2',
      text: 'Examine the switch port status: Port 3, which feeds Node C, indicates Link DOWN.',
      penalty: 15,
      order: 1,
    },
    {
      id: 'hint-network-stage-3',
      stageId: 'stage-3',
      text: 'The wireless access point is online. The correct path goes from Node C via WiFi to the AP, then to the switch, and into the gateway.',
      penalty: 20,
      order: 1,
    },
    {
      id: 'hint-network-stage-4',
      stageId: 'stage-4',
      text: 'The authorization code was granted in your Stage 3 intelligence clue: NET99.',
      penalty: 25,
      order: 1,
    },
  ],
  rewards: [
    {
      id: 'reward-network-stage-1-xp',
      type: 'XP',
      amount: 50,
    },
    {
      id: 'reward-network-stage-1-score',
      type: 'SCORE',
      amount: 100,
    },
    {
      id: 'reward-network-stage-2-xp',
      type: 'XP',
      amount: 50,
    },
    {
      id: 'reward-network-stage-2-score',
      type: 'SCORE',
      amount: 100,
    },
    {
      id: 'reward-network-stage-3-xp',
      type: 'XP',
      amount: 50,
    },
    {
      id: 'reward-stage-3-score',
      type: 'SCORE',
      amount: 100,
    },
    {
      id: 'reward-network-stage-3-clue-key',
      type: 'CLUE',
      value: 'Gateway Routing Authorization Code: NET99',
    },
    {
      id: 'reward-network-stage-4-xp',
      type: 'XP',
      amount: 100,
    },
    {
      id: 'reward-network-stage-4-score',
      type: 'SCORE',
      amount: 200,
    },
    {
      id: 'reward-network-stage-4-badge-repairer',
      type: 'BADGE',
      badgeId: 'NETWORK_REPAIRER',
      value: 'Network Repairer: Re-routed lost IoT nodes and restored mission-critical telemetry',
    },
  ],
  scene: {
    objects: [
      {
        id: 'central_gateway',
        name: 'Central IoT Gateway Hub',
        type: 'SERVER',
        position: [-1.5, 1.4, -4.0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-4',
        locked: true,
        visible: true,
        metadata: {
          role: 'Primary Gateway Aggregator',
        },
      },
      {
        id: 'router',
        name: 'Enterprise Core Router',
        type: 'ROUTER',
        position: [-1.5, 0.8, -4.0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-2',
        locked: true,
        visible: true,
        metadata: {
          role: 'Gateway Router',
        },
      },
      {
        id: 'network_switch',
        name: '24-Port Managed Switch',
        type: 'SWITCH',
        position: [-1.5, 1.1, -4.0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-2',
        locked: true,
        visible: true,
        metadata: {
          role: 'Layer 2 Switch',
        },
      },
      {
        id: 'wireless_ap',
        name: 'Industrial Wireless Access Point',
        type: 'ACCESS_POINT',
        position: [1.5, 2.5, -4.0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-3',
        locked: true,
        visible: true,
        metadata: {
          role: 'Wireless Mesh Bridge',
        },
      },
      {
        id: 'monitoring_screen',
        name: 'NOC Status Telemetry Display',
        type: 'DISPLAY',
        position: [0.0, 1.8, -4.8],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-1',
        locked: false,
        visible: true,
        metadata: {
          display: 'Node Health Dashboard',
        },
      },
      {
        id: 'sensor_nodes',
        name: 'Field Sensor Node Bench',
        type: 'EQUIPMENT',
        position: [2.5, 0.9, -2.5],
        rotation: [0, -Math.PI / 4, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-1',
        locked: false,
        visible: true,
        metadata: {
          nodes: 'Nodes A, B, C, D',
        },
      },
      {
        id: 'packet_console',
        name: 'Packet Route Selection Console',
        type: 'CONTROL_PANEL',
        position: [-3.5, 1.4, -2.0],
        rotation: [0, Math.PI / 3, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-3',
        locked: true,
        visible: true,
        metadata: {
          console: 'Routing Matrix Interface',
        },
      },
      {
        id: 'network_cabinet',
        name: 'Fiber Patch Enclosure',
        type: 'CONTAINER',
        position: [-4.5, 1.5, 0.5],
        rotation: [0, Math.PI / 2, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-2',
        locked: true,
        visible: true,
        metadata: {
          contents: 'Cat6A cables & optical transceivers',
        },
      },
      {
        id: 'exit_door',
        name: 'NOC Security Exit Portal',
        type: 'EXIT_DOOR',
        position: [4.5, 1.5, 0.0],
        rotation: [0, -Math.PI / 2, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-4',
        locked: true,
        visible: true,
        metadata: {
          securityLevel: 'NOC_INTERLOCK',
        },
      },
    ],
  },
};
