import { MissionDefinition } from '@missionx/shared';

export const POWER_GRID_CALIBRATION_DEFINITION: MissionDefinition = {
  id: 'mission-power-grid-04',
  slug: 'power-grid-calibration',
  title: 'Power Grid Calibration',
  domain: 'Electrical / Embedded Systems',
  difficulty: 'Hard',
  description:
    'A low-voltage DC microgrid test bench in the energy conversion lab has fallen out of calibration. Inspect digital sensor readings, calculate 12-bit ADC digitization counts, configure PWM duty cycles for target voltage regulation, and stabilize the load bank to unlock the laboratory exit portal.',
  briefing:
    'A simulated low-voltage power-control system has incorrect calibration values. Inspect readings, calculate ADC and PWM parameters, and stabilize the controller.',
  estimatedDuration: '15–20 min',
  learningObjectives: [
    'Calculate 12-bit ADC quantization counts (V_in / V_ref * 4096)',
    'Determine PWM duty cycle percentages for voltage synthesis',
    'Calculate electrical power dissipation across resistive test loads (P = V² / R)',
    'Understand safe low-voltage feedback loop regulation',
    'Execute power grid synchronization protocols',
  ],
  version: 1,
  settings: {
    allowHints: true,
    maxAttempts: 5,
    passScorePercentage: 70,
  },
  stages: [
    {
      id: 'stage-1',
      order: 1,
      title: 'Analyze ADC Quantization',
      objective: 'Calculate the expected digital conversion value for a 1.65 V analog input.',
      description:
        'The DC microgrid uses a 12-bit Analog-to-Digital Converter with a 3.3 V reference. Calculate the expected digital word corresponding to the 1.65 V midpoint sensor voltage.',
      interactionIds: [
        'inspect-adc-module',
        'inspect-voltage-display',
        'q1-adc-calc-interaction',
      ],
      questionIds: ['q1_adc_calc'],
      hintIds: ['hint-power-stage-1'],
      rewardIds: ['reward-power-stage-1-xp', 'reward-power-stage-1-score'],
    },
    {
      id: 'stage-2',
      order: 2,
      title: 'Configure PWM Voltage Regulator',
      objective: 'Determine the PWM duty cycle needed to synthesize an average 1.98 V from a 3.3 V rail.',
      description:
        'The power stage uses pulse-width modulation at 1 kHz to drive a step-down buck converter. Calculate the duty cycle percentage required to deliver 1.98 V.',
      interactionIds: [
        'inspect-pwm-controller',
        'q2-pwm-duty-interaction',
      ],
      questionIds: ['q2_pwm_duty'],
      hintIds: ['hint-power-stage-2'],
      rewardIds: ['reward-power-stage-2-xp', 'reward-power-stage-2-score'],
    },
    {
      id: 'stage-3',
      order: 3,
      title: 'Calibrate Load Bank Dissipation',
      objective: 'Calculate electrical power dissipation across the 10 Ω calibrated test load.',
      description:
        'Verify that power dissipation on the 10 Ω dummy load remains within the 0.5 W thermal envelope before locking the calibration parameters.',
      interactionIds: [
        'inspect-load-bank',
        'inspect-calibration-panel',
        'q3-load-calibration-interaction',
      ],
      questionIds: ['q3_load_calibration'],
      hintIds: ['hint-power-stage-3'],
      rewardIds: [
        'reward-power-stage-3-xp',
        'reward-power-stage-3-score',
        'reward-power-stage-3-clue-key',
      ],
    },
    {
      id: 'stage-4',
      order: 4,
      title: 'Synchronize Power Controller',
      objective: 'Enter the synchronization clearance code into the master power console to unlock the lab exit.',
      description:
        'Commit the validated calibration parameters into the non-volatile memory of the microgrid controller to unlock the safety blast door.',
      interactionIds: [
        'inspect-power-console',
        'q4-grid-stabilize-interaction',
      ],
      questionIds: ['q4_grid_stabilize'],
      hintIds: ['hint-power-stage-4'],
      rewardIds: [
        'reward-power-stage-4-xp',
        'reward-power-stage-4-score',
        'reward-power-stage-4-badge-calibrator',
      ],
      isFinalStage: true,
    },
  ],
  interactions: [
    {
      id: 'inspect-adc-module',
      type: 'INSPECT',
      targetObjectId: 'adc_module',
      stageId: 'stage-1',
      title: 'Inspect 12-Bit ADC Module',
      description: 'Check reference voltage and resolution of the conversion channel.',
      feedbackMessage: 'ADC Telemetry: Reference Voltage Vref = 3.30 V | Resolution: 12-Bit (4096 Counts) | Input Channel CH0 = 1.650 V.',
      config: {
        converterModel: 'MCP3208 12-Bit SPI ADC',
        vRef: '3.30 V (Precision Bandgap)',
        analogIn: '1.650 V DC',
        resolution: '12-bit (0 to 4095)',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'inspect-voltage-display',
      type: 'INSPECT',
      targetObjectId: 'voltage_display',
      stageId: 'stage-1',
      title: 'Inspect Low-Voltage Bus Meter',
      description: 'Observe digital voltmeter readouts on the control rack.',
      feedbackMessage: 'Voltmeter: Bus A = 3.30 V, Bus B = 1.65 V, Ripple = < 2 mV rms.',
      config: {
        meter: 'Digital Precision Panel Meter',
        voltage: '1.65 V DC',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q1-adc-calc-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'adc_module',
      stageId: 'stage-1',
      title: 'Submit Calculated ADC Value',
      questionId: 'q1_adc_calc',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'ADC conversion verified: 2048 counts (exact mid-scale point).',
    },
    {
      id: 'inspect-pwm-controller',
      type: 'INSPECT',
      targetObjectId: 'pwm_controller',
      stageId: 'stage-2',
      title: 'Inspect PWM Microcontroller Stage',
      description: 'Check pulse-width modulation timer parameters.',
      feedbackMessage: 'PWM Stage: Supply Rail = 3.3 V | Frequency = 1.0 kHz | Target Vavg = 1.98 V | Duty Register: Awaiting Calculation.',
      config: {
        driver: 'High-Efficiency Synchronous MOSFET Driver',
        carrierFreq: '1000 Hz',
        targetAverageVoltage: '1.98 V',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q2-pwm-duty-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'pwm_controller',
      stageId: 'stage-2',
      title: 'Configure PWM Duty Cycle',
      questionId: 'q2_pwm_duty',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Duty cycle verified: 60% modulation applied. Output locked to 1.98 V.',
    },
    {
      id: 'inspect-load-bank',
      type: 'INSPECT',
      targetObjectId: 'load_bank',
      stageId: 'stage-3',
      title: 'Inspect Calibrated Load Bank',
      description: 'Check high-precision non-inductive power resistor bank.',
      feedbackMessage: 'Load Bank: Resistance = 10.0 Ω (±0.1%) | Operating Voltage = 1.98 V | Max Thermal Rating = 2.0 W.',
      config: {
        resistorModel: 'Wirewound Non-Inductive Resistor Array',
        nominalResistance: '10.0 Ω',
        appliedVoltage: '1.98 V',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'inspect-calibration-panel',
      type: 'INSPECT',
      targetObjectId: 'calibration_panel',
      stageId: 'stage-3',
      title: 'Inspect Calibration Diagnostics Panel',
      description: 'Examine current and thermal sensors on the load rack.',
      feedbackMessage: 'Diagnostics: Current I = 0.198 A | Dissipation calculation required for stability sign-off.',
      config: {
        current: '0.198 A',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q3-load-calibration-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'load_bank',
      stageId: 'stage-3',
      title: 'Verify Power Dissipation',
      questionId: 'q3_load_calibration',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Power dissipation confirmed: 0.39 W (safely under 0.5 W limit).',
    },
    {
      id: 'inspect-power-console',
      type: 'INSPECT',
      targetObjectId: 'power_console',
      stageId: 'stage-4',
      title: 'Inspect Master Grid Control Console',
      description: 'Master power grid interface and safety relay terminal.',
      feedbackMessage: 'Microgrid Controller: All parameters in nominal safe envelope. Enter synchronization code to disengage exit interlock.',
      config: {
        status: 'GRID_EQUILIBRIUM_REACHED',
        interlock: 'ARMED_LOCKED',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q4-grid-stabilize-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'power_console',
      stageId: 'stage-4',
      title: 'Authorize Microgrid Synchronization',
      questionId: 'q4_grid_stabilize',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Synchronization accepted! Converter closed loop latched. Exit door opened.',
    },
  ],
  questions: [
    {
      id: 'q1_adc_calc',
      prompt: 'With a 3.3 V reference voltage and a 12-bit ADC (4096 quantization steps), what integer count corresponds to an analog input of 1.65 V (Count = Vin / Vref * 4096)?',
      type: 'multiple_choice',
      options: ['1024', '2048', '3072', '4096'],
      correctAnswer: '2048',
      explanation: 'Count = (1.65 V / 3.30 V) * 4096 = 0.5 * 4096 = 2048 counts.',
      points: 100,
      maxAttempts: 3,
      stageId: 'stage-1',
      learningObjective: 'Calculate 12-bit ADC quantization counts (V_in / V_ref * 4096)',
    },
    {
      id: 'q2_pwm_duty',
      prompt: 'What PWM duty cycle percentage is required to generate an average output voltage of 1.98 V from a 3.3 V DC power supply rail (Duty = Vout / Vin * 100%)?',
      type: 'multiple_choice',
      options: ['40%', '50%', '60%', '75%'],
      correctAnswer: '60%',
      explanation: 'Duty = (1.98 V / 3.30 V) * 100% = 0.60 * 100% = 60%.',
      points: 100,
      maxAttempts: 3,
      stageId: 'stage-2',
      learningObjective: 'Determine PWM duty cycle percentages for voltage synthesis',
    },
    {
      id: 'q3_load_calibration',
      prompt: 'If an average voltage of 1.98 V is applied across a 10 Ω resistive test load, calculate the power dissipation (P = V² / R):',
      type: 'multiple_choice',
      options: ['0.19 W', '0.39 W', '0.78 W', '1.98 W'],
      correctAnswer: '0.39 W',
      explanation: 'P = V² / R = (1.98)² / 10 = 3.9204 / 10 = 0.392 W ≈ 0.39 W.',
      points: 100,
      maxAttempts: 3,
      stageId: 'stage-3',
      learningObjective: 'Calculate electrical power dissipation across resistive test loads (P = V² / R)',
    },
    {
      id: 'q4_grid_stabilize',
      prompt: 'Enter the 6-character Power Calibration Clearance Code revealed upon verifying load stability to commit the feedback parameters and open the exit:',
      type: 'code',
      correctAnswer: 'GRID33',
      explanation: 'Code GRID33 commits the closed-loop PID constants into non-volatile EEPROM.',
      points: 200,
      maxAttempts: 5,
      stageId: 'stage-4',
      learningObjective: 'Execute power grid synchronization protocols',
    },
  ],
  hints: [
    {
      id: 'hint-power-stage-1',
      stageId: 'stage-1',
      text: 'Notice that 1.65 V is exactly half of the 3.3 V reference. Half of 4096 is 2048.',
      penalty: 15,
      order: 1,
    },
    {
      id: 'hint-power-stage-2',
      stageId: 'stage-2',
      text: 'Divide the target voltage by supply rail: 1.98 / 3.3 = 0.60, which equals 60%.',
      penalty: 15,
      order: 1,
    },
    {
      id: 'hint-power-stage-3',
      stageId: 'stage-3',
      text: 'Calculate: 1.98 * 1.98 = 3.92. Divide by 10 Ω resistance: 0.392 W ≈ 0.39 W.',
      penalty: 20,
      order: 1,
    },
    {
      id: 'hint-power-stage-4',
      stageId: 'stage-4',
      text: 'The synchronization code was awarded in your Stage 3 intelligence clue: GRID33.',
      penalty: 25,
      order: 1,
    },
  ],
  rewards: [
    {
      id: 'reward-power-stage-1-xp',
      type: 'XP',
      amount: 50,
    },
    {
      id: 'reward-power-stage-1-score',
      type: 'SCORE',
      amount: 100,
    },
    {
      id: 'reward-power-stage-2-xp',
      type: 'XP',
      amount: 50,
    },
    {
      id: 'reward-power-stage-2-score',
      type: 'SCORE',
      amount: 100,
    },
    {
      id: 'reward-power-stage-3-xp',
      type: 'XP',
      amount: 50,
    },
    {
      id: 'reward-power-stage-3-score',
      type: 'SCORE',
      amount: 100,
    },
    {
      id: 'reward-power-stage-3-clue-key',
      type: 'CLUE',
      value: 'Power Grid Calibration Code: GRID33 (Vavg = 1.98V, P = 0.39W)',
    },
    {
      id: 'reward-power-stage-4-xp',
      type: 'XP',
      amount: 100,
    },
    {
      id: 'reward-power-stage-4-score',
      type: 'SCORE',
      amount: 200,
    },
    {
      id: 'reward-power-stage-4-badge-calibrator',
      type: 'BADGE',
      badgeId: 'POWER_CALIBRATOR',
      value: 'Power Calibrator: Successfully tuned low-voltage ADC conversion and PWM regulation',
    },
  ],
  scene: {
    objects: [
      {
        id: 'dc_supply',
        name: 'Triple-Output Precision DC Supply',
        type: 'POWER_SOURCE',
        position: [-1.2, 1.2, -3.8],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-1',
        locked: false,
        visible: true,
        metadata: {
          railA: '3.3V DC',
        },
      },
      {
        id: 'adc_module',
        name: '12-Bit Analog Quantizer Submodule',
        type: 'SENSOR',
        position: [0.0, 1.1, -3.5],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-1',
        locked: false,
        visible: true,
        metadata: {
          adcType: 'MCP3208 12-Bit SPI',
        },
      },
      {
        id: 'voltage_display',
        name: 'Digital Bus Voltmeter',
        type: 'DISPLAY',
        position: [1.2, 1.3, -3.8],
        rotation: [0, -0.2, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-1',
        locked: false,
        visible: true,
        metadata: {
          readout: '1.65 V DC',
        },
      },
      {
        id: 'pwm_controller',
        name: 'PWM Buck Converter Stage',
        type: 'ACTUATOR',
        position: [0.0, 1.3, -3.0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-2',
        locked: true,
        visible: true,
        metadata: {
          pwmFreq: '1000 Hz',
        },
      },
      {
        id: 'load_bank',
        name: 'Precision Resistive Load Bank',
        type: 'EQUIPMENT',
        position: [-2.5, 0.9, -2.5],
        rotation: [0, Math.PI / 4, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-3',
        locked: true,
        visible: true,
        metadata: {
          load: '10 Ω Resistor Array',
        },
      },
      {
        id: 'calibration_panel',
        name: 'Thermal & Current Diagnostic Bay',
        type: 'DISPLAY',
        position: [-2.5, 1.6, -2.5],
        rotation: [0, Math.PI / 4, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-3',
        locked: true,
        visible: true,
        metadata: {
          diagnostics: 'Current shunt monitor',
        },
      },
      {
        id: 'power_console',
        name: 'Master Microgrid Controller',
        type: 'CONTROL_PANEL',
        position: [3.5, 1.5, -2.0],
        rotation: [0, -Math.PI / 3, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-4',
        locked: true,
        visible: true,
        metadata: {
          system: 'Closed Loop DC Microgrid',
        },
      },
      {
        id: 'cabinet_04',
        name: 'Calibration Standards Locker',
        type: 'CONTAINER',
        position: [-4.5, 1.5, 0.5],
        rotation: [0, Math.PI / 2, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-2',
        locked: true,
        visible: true,
        metadata: {
          contents: 'Precision voltage reference ICs & shunt resistors',
        },
      },
      {
        id: 'exit_door',
        name: 'High-Efficiency Lab Exit Portal',
        type: 'EXIT_DOOR',
        position: [4.5, 1.5, 0.0],
        rotation: [0, -Math.PI / 2, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-4',
        locked: true,
        visible: true,
        metadata: {
          lockType: 'POWER_BUS_INTERLOCK',
        },
      },
    ],
  },
};
