import { MissionDefinition } from '@missionx/shared';

export const RESCUE_THE_SERVER_ROOM_DEFINITION: MissionDefinition = {
  id: 'mission-server-room-01',
  slug: 'rescue-the-server-room',
  title: 'Rescue the Server Room',
  domain: 'IoT / Embedded Systems',
  difficulty: 'Medium',
  description:
    'A critical campus datacenter cluster is triggering thermal overload alarms. Enter the server room, analyze live environmental telemetry, diagnose the cooling failure, and restore normal operations before automatic emergency shutdown occurs.',
  briefing:
    'The server room is overheating. Determine whether the cooling system is functioning correctly.',
  estimatedDuration: '10–15 min',
  learningObjectives: [
    'Interpret temperature readings',
    'Interpret humidity readings',
    'Understand basic IoT sensor data',
    'Understand actuator behavior',
    'Apply basic embedded-system reasoning',
    'Make decisions from environmental telemetry',
  ],
  version: 1,
  settings: {
    allowHints: true,
    maxAttempts: 5,
    passScorePercentage: 70,
  },
  stages: [
    {
      id: 'stage-1',
      order: 1,
      title: 'Assess the Environment',
      objective: 'Inspect environmental sensors and determine whether thermal conditions are safe.',
      description:
        'Audible alarms are pinging datacenter monitoring. Access the ambient telemetry nodes and evaluate temperature and humidity against safe operational limits.',
      interactionIds: [
        'inspect-temp-sensor',
        'inspect-humidity-sensor',
        'q1-temp-safe-interaction',
      ],
      questionIds: ['q1_temp_safe'],
      hintIds: ['hint-stage-1'],
      rewardIds: ['reward-stage-1-xp', 'reward-stage-1-score'],
    },
    {
      id: 'stage-2',
      order: 2,
      title: 'Inspect the Cooling System',
      objective: 'Diagnose the status of the cooling fan, status LEDs, and warning buzzer.',
      description:
        'With thermal limits breached, investigate the Computer Room Air Conditioning (CRAC) unit and check why ventilation has ceased.',
      interactionIds: [
        'inspect-warning-led',
        'inspect-buzzer',
        'inspect-cooling-fan',
        'q2-cooling-diagnosis-interaction',
      ],
      questionIds: ['q2_cooling_diagnosis'],
      hintIds: ['hint-stage-2'],
      rewardIds: ['reward-stage-2-xp', 'reward-stage-2-score'],
    },
    {
      id: 'stage-3',
      order: 3,
      title: 'Check for Environmental Risk',
      objective: 'Inspect the condensate drainage tray to rule out liquid leakage hazards.',
      description:
        'Before re-energizing the high-power cooling circuit, confirm whether condensation or liquid overflow caused the breaker trip.',
      interactionIds: [
        'inspect-water-sensor',
        'inspect-drainage-tray',
        'q3-water-safety-interaction',
      ],
      questionIds: ['q3_water_safety'],
      hintIds: ['hint-stage-3'],
      rewardIds: [
        'reward-stage-3-xp',
        'reward-stage-3-score',
        'reward-stage-3-clue-breaker-code',
      ],
    },
    {
      id: 'stage-4',
      order: 4,
      title: 'Restore Safe Operation',
      objective: 'Access the control panel, enter the breaker authorization code, and restore cooling.',
      description:
        'Input the clearance code into the emergency control panel to reset the circuit breaker, restore fan rotation, and unlock the exit door.',
      interactionIds: ['inspect-control-panel', 'q4-cooling-restart-interaction'],
      questionIds: ['q4_cooling_restart'],
      hintIds: ['hint-stage-4'],
      rewardIds: [
        'reward-stage-4-xp',
        'reward-stage-4-score',
        'reward-stage-4-badge-server-savior',
      ],
      isFinalStage: true,
    },
  ],
  interactions: [
    {
      id: 'inspect-temp-sensor',
      type: 'INSPECT',
      targetObjectId: 'temperature_sensor',
      stageId: 'stage-1',
      title: 'Read Digital Temperature Probe',
      description: 'Check the real-time digital temperature telemetry on the intake rack probe.',
      feedbackMessage: 'Intake Probe DHT22 reports 31.8 °C. Safe operating envelope is 20 °C – 27 °C.',
      config: {
        sensorModel: 'DHT22 Digital Temperature Probe',
        currentTelemetry: '31.8 °C',
        status: 'CRITICAL OVERHEATING',
        safeEnvelope: '20.0 °C - 27.0 °C',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'inspect-humidity-sensor',
      type: 'INSPECT',
      targetObjectId: 'humidity_sensor',
      stageId: 'stage-1',
      title: 'Read Digital Humidity Probe',
      description: 'Check the relative humidity level in the server rack cold aisle.',
      feedbackMessage: 'Intake Probe DHT22 reports 68 % Relative Humidity. Safe envelope is 40 % – 60 %.',
      config: {
        sensorModel: 'DHT22 Digital Humidity Sensor',
        currentTelemetry: '68 % RH',
        status: 'ELEVATED HUMIDITY',
        safeEnvelope: '40 % - 60 % RH',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q1-temp-safe-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'temperature_sensor',
      stageId: 'stage-1',
      title: 'Evaluate Environmental Safety',
      questionId: 'q1_temp_safe',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Diagnostic confirmed: Ambient thermal threshold exceeded.',
    },
    {
      id: 'inspect-warning-led',
      type: 'INSPECT',
      targetObjectId: 'warning_led',
      stageId: 'stage-2',
      title: 'Inspect Primary Warning Beacon',
      description: 'Observe the visual indicator beacon atop the rack column.',
      feedbackMessage: 'Visual beacon is emitting high-frequency flashing amber strobe (CRAC Offline Alert).',
      config: {
        indicatorType: 'Industrial Strobe LED Beacon',
        color: 'Amber (590nm)',
        status: 'ACTIVE_PULSING',
        sourceTrigger: 'CRAC_BLOWER_POWER_LOSS',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'inspect-buzzer',
      type: 'INSPECT',
      targetObjectId: 'buzzer',
      stageId: 'stage-2',
      title: 'Inspect Acoustic Alarm Buzzer',
      description: 'Inspect the acoustic piezo buzzer housing.',
      feedbackMessage: 'Piezo transducer is silenced by silence button, but fault tone latch remains engaged.',
      config: {
        deviceType: 'Piezo Acoustic Alarm Transducer',
        outputDb: '85 dB at 1m',
        state: 'FAULT_LATCHED',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'inspect-cooling-fan',
      type: 'INSPECT',
      targetObjectId: 'cooling_fan',
      stageId: 'stage-2',
      title: 'Inspect Main Cooling Blower Impeller',
      description: 'Check the impeller blades and drive motor of the CRAC ventilation system.',
      feedbackMessage: 'Blower impeller is completely stationary. Tachometer reads 0 RPM. Breaker status: TRIPPED.',
      config: {
        unit: 'CRAC Dual Centrifugal Blower',
        motorRpm: 0,
        normalRpm: 2400,
        breakerStatus: 'OPEN (TRIPPED)',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q2-cooling-diagnosis-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'cooling_fan',
      stageId: 'stage-2',
      title: 'Submit Cooling Diagnostic',
      questionId: 'q2_cooling_diagnosis',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Fault root-cause identified: Blower circuit breaker tripped.',
    },
    {
      id: 'inspect-water-sensor',
      type: 'INSPECT',
      targetObjectId: 'water_sensor',
      stageId: 'stage-3',
      title: 'Inspect Resistive Water Sensor Grid',
      description: 'Verify whether moisture or liquid accumulation caused the circuit trip.',
      feedbackMessage: 'Resistive moisture detector indicates DRY (Resistance > 1M Ohm). Logic Level: LOW (0V).',
      config: {
        sensorType: 'Sub-floor Nickel Plated Liquid Sensor Grid',
        logicLevel: 'LOW (0.0 V)',
        state: 'DRY_NOMINAL',
        liquidDetected: false,
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'inspect-drainage-tray',
      type: 'INSPECT',
      targetObjectId: 'drainage_tray',
      stageId: 'stage-3',
      title: 'Inspect AC Condensate Pan',
      description: 'Check condensate collection pan under evaporator coils.',
      feedbackMessage: 'Condensate pan is clear. Gravity drain line is unimpeded. Safe to re-energize.',
      config: {
        drainPipe: 'Gravity Trap PVC 25mm',
        flowStatus: 'CLEAR',
        hazards: 'NONE',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q3-water-safety-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'water_sensor',
      stageId: 'stage-3',
      title: 'Verify Re-energization Safety',
      questionId: 'q3_water_safety',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Moisture safety confirmed: Clear to reset breaker.',
    },
    {
      id: 'inspect-control-panel',
      type: 'INSPECT',
      targetObjectId: 'control_panel',
      stageId: 'stage-4',
      title: 'Access Emergency Breaker Control Panel',
      description: 'Emergency electrical subpanel controlling CRAC blower auxiliary power.',
      feedbackMessage: 'Subpanel locked. 4-digit breaker clearance code required to engage main contactor.',
      config: {
        panelId: 'CRAC-AUX-SUBPANEL-01',
        busVoltage: '240V AC 3-Phase',
        contactorStatus: 'OPEN',
        keypadArmed: true,
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q4-cooling-restart-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'control_panel',
      stageId: 'stage-4',
      title: 'Enter Breaker Reset Authorization Code',
      questionId: 'q4_cooling_restart',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Code accepted! Breaker contactor engaged. Cooling fan spinning at 2400 RPM.',
    },
  ],
  questions: [
    {
      id: 'q1_temp_safe',
      prompt: 'Based on the digital sensor telemetry (31.8 °C), are thermal conditions inside the server room currently within safe limits?',
      type: 'multiple_choice',
      options: [
        'Yes - Conditions are nominal and within safe operational limits',
        'No - Server room is overheating above the 28.0°C safe threshold',
        'Inconclusive - More diagnostic data required',
      ],
      correctAnswer: 'No - Server room is overheating above the 28.0°C safe threshold',
      explanation:
        'Standard ASHRAE datacenter environmental guidelines stipulate a recommended temperature range between 18 °C and 27 °C. At 31.8 °C, thermal throttling and server hardware damage will occur.',
      points: 100,
      maxAttempts: 3,
      stageId: 'stage-1',
      learningObjective: 'Interpret temperature readings',
    },
    {
      id: 'q2_cooling_diagnosis',
      prompt: 'The CRAC blower fan reads 0 RPM and the breaker indicates TRIPPED. What action should be taken?',
      type: 'multiple_choice',
      options: [
        'Bypass safety breaker and force fan restart immediately',
        'Inspect cooling ductwork and check for coolant leaks or condensation hazards',
        'Wait for servers to thermally throttle',
      ],
      correctAnswer: 'Inspect cooling ductwork and check for coolant leaks or condensation hazards',
      explanation:
        'A tachometer reading of 0 RPM combined with an OPEN/TRIPPED circuit breaker requires physical hazard verification prior to breaker reset.',
      points: 100,
      maxAttempts: 3,
      stageId: 'stage-2',
      learningObjective: 'Understand actuator behavior',
    },
    {
      id: 'q3_water_safety',
      prompt: 'The sub-floor water sensor grid reads DRY (0.0 V). Is it electrically safe to reset the main cooling circuit breaker?',
      type: 'multiple_choice',
      options: [
        'Yes - Drainage is clear with no water hazard detected; proceed to breaker override',
        'No - Active water pooling detected under rack floor',
        'Shut down entire facility power main immediately',
      ],
      correctAnswer: 'Yes - Drainage is clear with no water hazard detected; proceed to breaker override',
      explanation:
        'Because the condensate tray is clear and the sensor grid reads 0.0V (DRY), there is no liquid short hazard preventing breaker re-energization.',
      points: 100,
      maxAttempts: 3,
      stageId: 'stage-3',
      learningObjective: 'Make decisions from environmental telemetry',
    },
    {
      id: 'q4_cooling_restart',
      prompt: 'Enter the 4-digit Breaker Authorization Clearance Code retrieved from the safety protocol logs to reset the cooling circuit breaker:',
      type: 'code',
      correctAnswer: '4180',
      explanation: 'Code 4180 clears the fault register and closes the main cooling contactor.',
      points: 200,
      maxAttempts: 5,
      stageId: 'stage-4',
      learningObjective: 'Apply basic embedded-system reasoning',
    },
  ],
  hints: [
    {
      id: 'hint-stage-1',
      stageId: 'stage-1',
      text: 'Examine standard ASHRAE datacenter limits. Safe server room air intake should not exceed 27 °C. The current reading is 31.8 °C.',
      penalty: 15,
      order: 1,
    },
    {
      id: 'hint-stage-2',
      stageId: 'stage-2',
      text: 'Check the cooling fan inspection details. Notice the tachometer is at 0 RPM and the electrical circuit breaker is tripped open.',
      penalty: 20,
      order: 1,
    },
    {
      id: 'hint-stage-3',
      stageId: 'stage-3',
      text: 'Check the water sensor voltage: 0.0 V (LOW) indicates dry conditions. Since no water is present, re-energizing the circuit is safe.',
      penalty: 20,
      order: 1,
    },
    {
      id: 'hint-stage-4',
      stageId: 'stage-4',
      text: 'The 4-digit clearance code was revealed in your Stage 3 intelligence clue: 4180.',
      penalty: 25,
      order: 1,
    },
  ],
  rewards: [
    {
      id: 'reward-stage-1-xp',
      type: 'XP',
      amount: 50,
    },
    {
      id: 'reward-stage-1-score',
      type: 'SCORE',
      amount: 100,
    },
    {
      id: 'reward-stage-2-xp',
      type: 'XP',
      amount: 50,
    },
    {
      id: 'reward-stage-2-score',
      type: 'SCORE',
      amount: 100,
    },
    {
      id: 'reward-stage-3-xp',
      type: 'XP',
      amount: 50,
    },
    {
      id: 'reward-stage-3-score',
      type: 'SCORE',
      amount: 100,
    },
    {
      id: 'reward-stage-3-clue-breaker-code',
      type: 'CLUE',
      value: 'Breaker Authorization Clearance Code is 4180',
    },
    {
      id: 'reward-stage-4-xp',
      type: 'XP',
      amount: 100,
    },
    {
      id: 'reward-stage-4-score',
      type: 'SCORE',
      amount: 200,
    },
    {
      id: 'reward-stage-4-badge-server-savior',
      type: 'BADGE',
      badgeId: 'SERVER_SAVIOR',
      value: 'Server Savior: Restored datacenter cooling during critical thermal crisis',
    },
  ],
  scene: {
    objects: [
      {
        id: 'temperature_sensor',
        name: 'Ambient Temperature Sensor',
        type: 'SENSOR',
        position: [2.5, 1.8, -3.0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-1',
        locked: false,
        visible: true,
        metadata: {
          sensorType: 'DHT22 Digital Temperature Sensor',
          measurementUnit: 'Celsius (°C)',
        },
      },
      {
        id: 'humidity_sensor',
        name: 'Ambient Humidity Probe',
        type: 'SENSOR',
        position: [2.8, 1.8, -3.0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-1',
        locked: false,
        visible: true,
        metadata: {
          sensorType: 'DHT22 Digital Humidity Sensor',
          measurementUnit: '% Relative Humidity',
        },
      },
      {
        id: 'cooling_fan',
        name: 'Main Cooling Blower Unit',
        type: 'ACTUATOR',
        position: [-2.0, 1.2, -4.5],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-2',
        locked: true,
        visible: true,
        metadata: {
          actuatorType: 'CRAC Centrifugal Blower Fan',
        },
      },
      {
        id: 'warning_led',
        name: 'Diagnostic Alert Beacon',
        type: 'ACTUATOR',
        position: [-1.5, 2.2, -4.0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-2',
        locked: true,
        visible: true,
        metadata: {
          indicatorType: 'Amber Strobe Warning LED',
        },
      },
      {
        id: 'buzzer',
        name: 'Piezo Alarm Horn',
        type: 'ACTUATOR',
        position: [-1.2, 2.2, -4.0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-2',
        locked: true,
        visible: true,
        metadata: {
          deviceType: 'Acoustic Piezo Buzzer',
        },
      },
      {
        id: 'water_sensor',
        name: 'Condensate Liquid Grid',
        type: 'SENSOR',
        position: [-2.0, 0.1, -4.5],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-3',
        locked: true,
        visible: true,
        metadata: {
          sensorType: 'Sub-floor Moisture Grid',
        },
      },
      {
        id: 'drainage_tray',
        name: 'AC Condensate Drain Tray',
        type: 'ENVIRONMENT',
        position: [-2.0, 0.05, -4.5],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-3',
        locked: true,
        visible: true,
        metadata: {
          structure: 'Gravity Drain Pan',
        },
      },
      {
        id: 'control_panel',
        name: 'Emergency Breaker Subpanel',
        type: 'CONTROL_PANEL',
        position: [0.0, 1.5, -4.8],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-4',
        locked: true,
        visible: true,
        metadata: {
          panelType: 'CRAC Circuit Breaker Control Station',
        },
      },
      {
        id: 'cabinet_01',
        name: 'Maintenance Supply Locker',
        type: 'CONTAINER',
        position: [5.5, 1.5, -3.0],
        rotation: [0, -Math.PI / 2, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-2',
        locked: true,
        visible: true,
        metadata: {
          contents: 'Insulated tools and safety equipment',
        },
      },
      {
        id: 'exit_door',
        name: 'Facility Blast Exit Door',
        type: 'EXIT_DOOR',
        position: [4.0, 1.5, 0.0],
        rotation: [0, -Math.PI / 2, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-4',
        locked: true,
        visible: true,
        metadata: {
          securityLevel: 'MAXIMUM_ISOLATION',
        },
      },
    ],
  },
};
