import { MissionDefinition } from '@missionx/shared';

export const SIGNAL_IN_THE_LAB_DEFINITION: MissionDefinition = {
  id: 'mission-signal-lab-02',
  slug: 'signal-in-the-lab',
  title: 'Signal in the Lab',
  domain: 'Electronics / Signals & Systems',
  difficulty: 'Medium',
  description:
    'A precision signal processing experiment in the advanced electronics lab has drifted out of tolerance. High-frequency noise is degrading the channel. Inspect the oscilloscope trace, calculate fundamental signal parameters, select the optimal analog filter topology, and calibrate the measurement console to restore clean transmission and unlock the lab exit.',
  briefing:
    'A laboratory signal-processing experiment has malfunctioned. Inspect the waveform, identify its properties, and configure the correct filter topology.',
  estimatedDuration: '12–18 min',
  learningObjectives: [
    'Analyze analog waveform telemetry on an oscilloscope',
    'Calculate signal period from frequency (T = 1/f)',
    'Identify filter topologies (Low-pass, High-pass, Band-pass)',
    'Understand frequency attenuation and noise suppression',
    'Configure precision instrumentation consoles',
  ],
  version: 1,
  settings: {
    allowHints: true,
    maxAttempts: 5,
    passScorePercentage: 70,
  },
  stages: [
    {
      id: 'stage-1',
      order: 1,
      title: 'Analyze the Waveform',
      objective: 'Inspect the digital storage oscilloscope and identify fundamental waveform properties.',
      description:
        'A test signal is active on Channel 1. Inspect the oscilloscope display to determine the fundamental waveform shape, peak-to-peak amplitude, and operating frequency.',
      interactionIds: [
        'inspect-oscilloscope',
        'inspect-signal-generator',
        'q1-waveform-freq-interaction',
      ],
      questionIds: ['q1_signal_freq'],
      hintIds: ['hint-signal-stage-1'],
      rewardIds: ['reward-signal-stage-1-xp', 'reward-signal-stage-1-score'],
    },
    {
      id: 'stage-2',
      order: 2,
      title: 'Calculate Signal Period',
      objective: 'Calculate the fundamental period of the 1000 Hz reference sinusoid.',
      description:
        'To properly synchronize timebase triggering, determine the exact mathematical period in milliseconds corresponding to the measured 1 kHz frequency.',
      interactionIds: [
        'inspect-breadboard',
        'q2-signal-period-interaction',
      ],
      questionIds: ['q2_signal_period'],
      hintIds: ['hint-signal-stage-2'],
      rewardIds: ['reward-signal-stage-2-xp', 'reward-signal-stage-2-score'],
    },
    {
      id: 'stage-3',
      order: 3,
      title: 'Select Filter Topology',
      objective: 'Evaluate harmonic noise and select the appropriate filter circuit to eliminate high-frequency distortion.',
      description:
        'Spectral analysis reveals unwanted electromagnetic interference above 5 kHz corrupting the 1 kHz fundamental tone. Select the correct active filter topology.',
      interactionIds: [
        'inspect-filter-module',
        'q3-filter-select-interaction',
      ],
      questionIds: ['q3_filter_select'],
      hintIds: ['hint-signal-stage-3'],
      rewardIds: [
        'reward-signal-stage-3-xp',
        'reward-signal-stage-3-score',
        'reward-signal-stage-3-clue-key',
      ],
    },
    {
      id: 'stage-4',
      order: 4,
      title: 'Calibrate Measurement Console',
      objective: 'Enter the filter authorization key to calibrate output stages and release the laboratory exit lock.',
      description:
        'Authorize the calibrated signal matrix at the primary instrumentation console to verify low Total Harmonic Distortion (THD) and disengage the safety interlock.',
      interactionIds: [
        'inspect-measurement-console',
        'q4-signal-calibrate-interaction',
      ],
      questionIds: ['q4_signal_calibrate'],
      hintIds: ['hint-signal-stage-4'],
      rewardIds: [
        'reward-signal-stage-4-xp',
        'reward-signal-stage-4-score',
        'reward-signal-stage-4-badge-detective',
      ],
      isFinalStage: true,
    },
  ],
  interactions: [
    {
      id: 'inspect-oscilloscope',
      type: 'INSPECT',
      targetObjectId: 'oscilloscope',
      stageId: 'stage-1',
      title: 'Inspect Digital Storage Oscilloscope',
      description: 'Observe the real-time Channel 1 trace on the 200 MHz DSO screen.',
      feedbackMessage: 'DSO Ch1 Display: Sine Wave | Vpp: 2.00 V | Frequency: 1000 Hz (1.00 kHz) | Time/Div: 250 µs.',
      config: {
        instrument: 'Rigol DS1054Z 4-Ch Digital Storage Oscilloscope',
        channel: 'CH1 Active (1 MΩ DC)',
        waveformType: 'Pure Sinusoid',
        frequency: '1000 Hz',
        amplitudeVpp: '2.00 V',
        noiseSpikes: 'Active above 5 kHz',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'inspect-signal-generator',
      type: 'INSPECT',
      targetObjectId: 'signal_generator',
      stageId: 'stage-1',
      title: 'Inspect Arbitrary Function Generator',
      description: 'Examine output parameters configured on the signal synthesizer.',
      feedbackMessage: 'Function Generator Output: CH1 ENABLED | 1.000 kHz Sine | Offset: 0.00 V | Load: High-Z.',
      config: {
        instrument: 'Siglent SDG1032X Function Generator',
        mode: 'Continuous Synthesized CW',
        outputImpedance: '50 Ω',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q1-waveform-freq-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'oscilloscope',
      stageId: 'stage-1',
      title: 'Confirm Measured Signal Frequency',
      questionId: 'q1_signal_freq',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Frequency telemetry verified: 1000 Hz fundamental identified.',
    },
    {
      id: 'inspect-breadboard',
      type: 'INSPECT',
      targetObjectId: 'breadboard',
      stageId: 'stage-2',
      title: 'Inspect Solderless Breadboard Prototype',
      description: 'Check passive RC components wired on the prototyping bench.',
      feedbackMessage: 'Prototyping array contains 10 kΩ precision metal film resistors and 15 nF ceramic capacitors.',
      config: {
        benchArea: 'Analog Prototyping Station',
        componentR: '10 kΩ (1% Tolerance)',
        componentC: '15 nF Film Capacitor',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q2-signal-period-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'breadboard',
      stageId: 'stage-2',
      title: 'Submit Calculated Signal Period',
      questionId: 'q2_signal_period',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Calculated period correct: T = 1 ms (1000 µs). Timebase synchronized.',
    },
    {
      id: 'inspect-filter-module',
      type: 'INSPECT',
      targetObjectId: 'filter_module',
      stageId: 'stage-3',
      title: 'Inspect Active Filter Submodule',
      description: 'Operational amplifier filter bank with selectable transfer functions.',
      feedbackMessage: 'Filter Bank: High-frequency ripple > 5 kHz detected on input bus. Passband must pass 1 kHz unattenuated.',
      config: {
        opAmpModel: 'TL072 Dual Low-Noise JFET Op-Amp',
        designCutoff: 'fc = 2.5 kHz (-3dB Butterworth)',
        status: 'AWAITING_TOPOLOGY_LATCH',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q3-filter-select-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'filter_module',
      stageId: 'stage-3',
      title: 'Select Correct Noise Suppression Filter',
      questionId: 'q3_filter_select',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Low-pass filter configuration accepted! High-frequency noise attenuated by -40 dB/decade.',
    },
    {
      id: 'inspect-measurement-console',
      type: 'INSPECT',
      targetObjectId: 'measurement_console',
      stageId: 'stage-4',
      title: 'Inspect Main Measurement Console',
      description: 'Central calibration terminal and automated test equipment (ATE) interface.',
      feedbackMessage: 'ATE Console ready for final calibration lock. Enter the filter authorization code to release exit portal.',
      config: {
        consoleId: 'LAB-ATE-STATION-02',
        thdPercent: '0.04% (Clean Harmonic Floor)',
        interlockStatus: 'ARMED_LOCKED',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q4-signal-calibrate-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'measurement_console',
      stageId: 'stage-4',
      title: 'Authorize Final Calibration Sequence',
      questionId: 'q4_signal_calibrate',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Key verified! Clean 1 kHz sine output latched. Laboratory exit portal unlocked.',
    },
  ],
  questions: [
    {
      id: 'q1_signal_freq',
      prompt: 'Reviewing the oscilloscope measurement readouts on Channel 1, what is the fundamental frequency of the test sine wave?',
      type: 'multiple_choice',
      options: ['500 Hz', '1000 Hz', '2500 Hz', '5000 Hz'],
      correctAnswer: '1000 Hz',
      explanation: 'The oscilloscope hardware frequency counter and on-screen telemetry indicate a frequency of exactly 1000 Hz (1 kHz).',
      points: 100,
      maxAttempts: 3,
      stageId: 'stage-1',
      learningObjective: 'Analyze analog waveform telemetry on an oscilloscope',
    },
    {
      id: 'q2_signal_period',
      prompt: 'For a sinusoidal waveform with frequency f = 1000 Hz, calculate the exact period (T = 1 / f):',
      type: 'multiple_choice',
      options: ['0.1 ms', '1 ms', '10 ms', '100 ms'],
      correctAnswer: '1 ms',
      explanation: 'T = 1 / f = 1 / 1000 s = 0.001 s = 1 ms.',
      points: 100,
      maxAttempts: 3,
      stageId: 'stage-2',
      learningObjective: 'Calculate signal period from frequency (T = 1/f)',
    },
    {
      id: 'q3_filter_select',
      prompt: 'To eliminate unwanted high-frequency interference (> 5 kHz) while permitting the 1 kHz desired signal to pass unattenuated, which filter topology must be selected?',
      type: 'multiple_choice',
      options: [
        'Low-pass filter',
        'High-pass filter',
        'Band-stop (Notch) filter at 1 kHz',
        'All-pass filter',
      ],
      correctAnswer: 'Low-pass filter',
      explanation:
        'A Low-pass filter allows signals with frequencies below its cutoff frequency (fc ≈ 2.5 kHz) to pass through, while attenuating all frequencies above the cutoff, eliminating the > 5 kHz interference.',
      points: 100,
      maxAttempts: 3,
      stageId: 'stage-3',
      learningObjective: 'Identify filter topologies (Low-pass, High-pass, Band-pass)',
    },
    {
      id: 'q4_signal_calibrate',
      prompt: 'Enter the 5-character Calibration Authorization Code revealed upon engaging the low-pass filter to latch the ATE output and unlock the door:',
      type: 'code',
      correctAnswer: 'RC741',
      explanation: 'Code RC741 confirms active feedback loop stabilization on the OP-AMP filter bus.',
      points: 200,
      maxAttempts: 5,
      stageId: 'stage-4',
      learningObjective: 'Configure precision instrumentation consoles',
    },
  ],
  hints: [
    {
      id: 'hint-signal-stage-1',
      stageId: 'stage-1',
      text: 'Look at the frequency/channel information on the oscilloscope. The waveform repeats once every 1 ms.',
      penalty: 15,
      order: 1,
    },
    {
      id: 'hint-signal-stage-2',
      stageId: 'stage-2',
      text: 'Use T = 1/f. For 1000 Hz, the period is 0.001 seconds.',
      penalty: 15,
      order: 1,
    },
    {
      id: 'hint-signal-stage-3',
      stageId: 'stage-3',
      text: 'A low-pass filter allows lower frequencies through while reducing higher-frequency components.',
      penalty: 20,
      order: 1,
    },
    {
      id: 'hint-signal-stage-4',
      stageId: 'stage-4',
      text: 'Inspect the filter module and calibration information around the electronics bench.',
      penalty: 25,
      order: 1,
    },
  ],
  rewards: [
    {
      id: 'reward-signal-stage-1-xp',
      type: 'XP',
      amount: 50,
    },
    {
      id: 'reward-signal-stage-1-score',
      type: 'SCORE',
      amount: 100,
    },
    {
      id: 'reward-signal-stage-2-xp',
      type: 'XP',
      amount: 50,
    },
    {
      id: 'reward-signal-stage-2-score',
      type: 'SCORE',
      amount: 100,
    },
    {
      id: 'reward-signal-stage-3-xp',
      type: 'XP',
      amount: 50,
    },
    {
      id: 'reward-signal-stage-3-score',
      type: 'SCORE',
      amount: 100,
    },
    {
      id: 'reward-signal-stage-3-clue-key',
      type: 'CLUE',
      value: 'Filter Calibration Key: RC741 (Cutoff fc = 2.5 kHz)',
    },
    {
      id: 'reward-signal-stage-4-xp',
      type: 'XP',
      amount: 100,
    },
    {
      id: 'reward-signal-stage-4-score',
      type: 'SCORE',
      amount: 200,
    },
    {
      id: 'reward-signal-stage-4-badge-detective',
      type: 'BADGE',
      badgeId: 'SIGNAL_DETECTIVE',
      value: 'Signal Detective: Successfully synthesized and filtered distorted laboratory waveforms',
    },
  ],
  scene: {
    objects: [
      {
        id: 'workbench',
        name: 'Electronics ESD Workbench',
        type: 'FURNITURE',
        position: [0.0, 0.8, -3.5],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-1',
        locked: false,
        visible: true,
        metadata: {
          surface: 'Anti-Static Dissipative Rubber Top',
        },
      },
      {
        id: 'oscilloscope',
        name: 'Digital Storage Oscilloscope',
        type: 'SENSOR',
        position: [-1.2, 1.25, -3.5],
        rotation: [0, 0.15, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-1',
        locked: false,
        visible: true,
        metadata: {
          screenContent: '1000 Hz Sine Wave',
        },
      },
      {
        id: 'signal_generator',
        name: 'Arbitrary Function Generator',
        type: 'INSTRUMENT',
        position: [1.2, 1.25, -3.5],
        rotation: [0, -0.15, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-1',
        locked: false,
        visible: true,
        metadata: {
          outputChannel: 'CH1 1 kHz',
        },
      },
      {
        id: 'breadboard',
        name: 'Prototyping Breadboard',
        type: 'EQUIPMENT',
        position: [0.0, 1.05, -3.2],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-2',
        locked: true,
        visible: true,
        metadata: {
          circuit: 'Passive RC Network',
        },
      },
      {
        id: 'filter_module',
        name: 'Active Filter Selector Module',
        type: 'ACTUATOR',
        position: [0.0, 1.35, -3.8],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-3',
        locked: true,
        visible: true,
        metadata: {
          filterType: 'Selectable Active Op-Amp Bank',
        },
      },
      {
        id: 'measurement_console',
        name: 'Main Instrumentation Console',
        type: 'CONTROL_PANEL',
        position: [3.5, 1.5, -2.0],
        rotation: [0, -Math.PI / 3, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-4',
        locked: true,
        visible: true,
        metadata: {
          system: 'Automated Test Console',
        },
      },
      {
        id: 'cabinet_02',
        name: 'Precision Component Cabinet',
        type: 'CONTAINER',
        position: [-4.5, 1.5, -1.0],
        rotation: [0, Math.PI / 2, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-2',
        locked: true,
        visible: true,
        metadata: {
          contents: 'Precision metal-film resistors & silver mica capacitors',
        },
      },
      {
        id: 'exit_door',
        name: 'Laboratory Safety Exit Door',
        type: 'EXIT_DOOR',
        position: [4.5, 1.5, 0.0],
        rotation: [0, -Math.PI / 2, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-4',
        locked: true,
        visible: true,
        metadata: {
          interlock: 'AUTOMATED_ATE_LATCH',
        },
      },
    ],
  },
};
