import { MissionDefinition } from '@missionx/shared';

export const THE_SMART_GREENHOUSE_MYSTERY_DEFINITION: MissionDefinition = {
  id: 'mission-greenhouse-05',
  slug: 'smart-greenhouse-mystery',
  title: 'The Smart Greenhouse Mystery',
  domain: 'IoT / Automation & Agriculture',
  difficulty: 'Medium',
  description:
    'An automated precision research greenhouse has fallen out of homeostasis. Crops are undergoing stress due to depleted soil moisture, escalating ambient temperatures, and inadequate lighting. Analyze multi-spectral telemetry, activate pulse irrigation pumps, engage climate exhaust ventilation, synchronize full-spectrum LED grow lights, and restore total environmental balance to unlock the botanical facility exit.',
  briefing:
    'A smart greenhouse is no longer maintaining the correct automated environmental conditions. Inspect sensor readings and restore the automated environment.',
  estimatedDuration: '12–15 min',
  learningObjectives: [
    'Interpret multi-channel agricultural IoT telemetry (moisture, lux, temp, RH)',
    'Identify soil moisture thresholds triggering automated drip irrigation',
    'Calculate cooling airflow requirements for convective plant canopy regulation',
    'Understand full-spectrum LED photoperiod scheduling in controlled environments',
    'Execute automated environmental equilibrium sequences',
  ],
  version: 1,
  settings: {
    allowHints: true,
    maxAttempts: 5,
    passScorePercentage: 70,
  },
  stages: [
    {
      id: 'stage-1',
      order: 1,
      title: 'Analyze Environmental Telemetry',
      objective: 'Inspect greenhouse sensors and isolate which critical parameter is below its healthy vegetative threshold.',
      description:
        'Botanical monitoring alerts indicate canopy stress. Access the environmental sensor node array and evaluate temperature, humidity, light intensity, and volumetric soil water content.',
      interactionIds: [
        'inspect-environmental-sensors',
        'inspect-plant-beds',
        'q1-greenhouse-issue-interaction',
      ],
      questionIds: ['q1_greenhouse_issue'],
      hintIds: ['hint-greenhouse-stage-1'],
      rewardIds: ['reward-greenhouse-stage-1-xp', 'reward-greenhouse-stage-1-score'],
    },
    {
      id: 'stage-2',
      order: 2,
      title: 'Automate Precision Irrigation',
      objective: 'Trigger precision drip irrigation to restore root zone moisture above 50%.',
      description:
        'With soil moisture critically depleted at 31%, inspect the main water storage reservoir and dispatch the automated pump actuation command to re-saturate root modules.',
      interactionIds: [
        'inspect-irrigation-system',
        'inspect-water-tank',
        'q2-irrigation-action-interaction',
      ],
      questionIds: ['q2_irrigation_action'],
      hintIds: ['hint-greenhouse-stage-2'],
      rewardIds: ['reward-greenhouse-stage-2-xp', 'reward-greenhouse-stage-2-score'],
    },
    {
      id: 'stage-3',
      order: 3,
      title: 'Regulate Canopy Ventilation',
      objective: 'Engage climate exhaust ventilation to bring ambient canopy temperatures from 29°C down to 24°C.',
      description:
        'Radiative solar gain has elevated temperatures to 29°C. Configure convective exhaust louvers and ventilation fans to evacuate hot air and normalize climate.',
      interactionIds: [
        'inspect-ventilation-fan',
        'q3-ventilation-cooling-interaction',
      ],
      questionIds: ['q3_ventilation_cooling'],
      hintIds: ['hint-greenhouse-stage-3'],
      rewardIds: [
        'reward-greenhouse-stage-3-xp',
        'reward-greenhouse-stage-3-score',
        'reward-greenhouse-stage-3-clue-key',
      ],
    },
    {
      id: 'stage-4',
      order: 4,
      title: 'Synchronize Photoperiod Lighting',
      objective: 'Input the greenhouse equilibrium key to synchronize full-spectrum grow lights and open the facility exit.',
      description:
        'Authorize supplemental full-spectrum photosynthetic photon flux density (PPFD) grow light arrays at the central environmental console to achieve total biological equilibrium and release the exit.',
      interactionIds: [
        'inspect-grow-lights',
        'inspect-greenhouse-console',
        'q4-grow-light-sync-interaction',
      ],
      questionIds: ['q4_grow_light_sync'],
      hintIds: ['hint-greenhouse-stage-4'],
      rewardIds: [
        'reward-greenhouse-stage-4-xp',
        'reward-greenhouse-stage-4-score',
        'reward-greenhouse-stage-4-badge-engineer',
      ],
      isFinalStage: true,
    },
  ],
  interactions: [
    {
      id: 'inspect-environmental-sensors',
      type: 'INSPECT',
      targetObjectId: 'environmental_sensors',
      stageId: 'stage-1',
      title: 'Inspect Multi-Channel Sensor Node',
      description: 'Check ambient temperature, relative humidity, and soil capacitance metrics.',
      feedbackMessage: 'Sensor Telemetry: Ambient Temp: 29.0 °C (Elevated) | Humidity: 52 % | Soil Moisture: 31 % (CRITICAL LOW; safe: 50–70%) | Light: 120 µmol/m²s (LOW).',
      config: {
        sensorType: 'Integrated Agricultural IoT Station',
        temperature: '29.0 °C',
        humidity: '52 % RH',
        soilMoisture: '31 % Volumetric Water Content',
        lightLevel: '120 µmol/m²s PAR',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'inspect-plant-beds',
      type: 'INSPECT',
      targetObjectId: 'plant_beds',
      stageId: 'stage-1',
      title: 'Inspect Hydroponic Growing Beds',
      description: 'Observe vegetative crop condition in row A.',
      feedbackMessage: 'Foliage exhibits early moisture stress. Root substrate is dry to the touch.',
      config: {
        crop: 'High-Density Microgreen & Vine Matrix',
        condition: 'MILD_WILTING_DETECTED',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q1-greenhouse-issue-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'environmental_sensors',
      stageId: 'stage-1',
      title: 'Diagnose Primary Environmental Deficit',
      questionId: 'q1_greenhouse_issue',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Deficit identified: Soil moisture is at 31% (critically below 50% minimum threshold).',
    },
    {
      id: 'inspect-irrigation-system',
      type: 'INSPECT',
      targetObjectId: 'irrigation_system',
      stageId: 'stage-2',
      title: 'Inspect Drip Irrigation Manifold',
      description: 'Check solenoid valves and pressure regulators on the drip lines.',
      feedbackMessage: 'Irrigation Manifold: Solenoid 1 & 2 CLOSED. Line Pressure = 0 PSI. Pump Relay = IDLE.',
      config: {
        system: 'Pressure-Compensating Drip Manifold',
        pumpStatus: 'STANDBY',
        waterPressure: '0.0 Bar',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'inspect-water-tank',
      type: 'INSPECT',
      targetObjectId: 'water_tank',
      stageId: 'stage-2',
      title: 'Inspect Nutrient Water Reservoir',
      description: 'Check level and pH of the central nutrient solution tank.',
      feedbackMessage: 'Reservoir Level: 880 Liters (88% Full) | pH: 6.2 (Optimal) | EC: 1.8 mS/cm.',
      config: {
        tankCapacity: '1000 Liters',
        currentFill: '880 Liters',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q2-irrigation-action-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'irrigation_system',
      stageId: 'stage-2',
      title: 'Dispatch Irrigation Actuation Command',
      questionId: 'q2_irrigation_action',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Command dispatched: Drip pump energized! Moisture rising steadily from 31% to 62%.',
    },
    {
      id: 'inspect-ventilation-fan',
      type: 'INSPECT',
      targetObjectId: 'ventilation_fan',
      stageId: 'stage-3',
      title: 'Inspect Climate Exhaust Fan',
      description: 'Examine primary air exchange blower on the north greenhouse gable.',
      feedbackMessage: 'Exhaust Fan: LOUVERS CLOSED | Motor 0 RPM | Heat accumulation at canopy level: +4.0 °C.',
      config: {
        actuator: 'Gable Convective Louver Fan',
        airflowRating: '3200 CFM',
        state: 'INACTIVE',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q3-ventilation-cooling-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'ventilation_fan',
      stageId: 'stage-3',
      title: 'Engage Climate Exhaust Ventilation',
      questionId: 'q3_ventilation_cooling',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Ventilation engaged! Louvers open, fan spinning. Temperature cooling rapidly from 29°C to 24°C.',
    },
    {
      id: 'inspect-grow-lights',
      type: 'INSPECT',
      targetObjectId: 'grow_lights',
      stageId: 'stage-4',
      title: 'Inspect Full-Spectrum LED Grow Lights',
      description: 'Check overhead horticulture lighting bars.',
      feedbackMessage: 'Grow Lights: Standby mode. Ready for full PAR spectrum engagement.',
      config: {
        lightFixture: 'Samsung LM301H Full Spectrum LED Array',
        parOutput: '650 µmol/m²s',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'inspect-greenhouse-console',
      type: 'INSPECT',
      targetObjectId: 'greenhouse_console',
      stageId: 'stage-4',
      title: 'Inspect Central Climate Console',
      description: 'Master climate automation computer terminal.',
      feedbackMessage: 'Automation Terminal: Moisture = 62% (NOMINAL) | Temp = 24.2 °C (NOMINAL) | Enter equilibrium code to latch lighting and exit door.',
      config: {
        terminal: 'Automated Precision Agriculture Engine',
        status: 'READY_FOR_EQUILIBRIUM_LATCH',
      },
      successEvent: 'OBJECT_INSPECTED',
    },
    {
      id: 'q4-grow-light-sync-interaction',
      type: 'ANSWER_QUESTION',
      targetObjectId: 'greenhouse_console',
      stageId: 'stage-4',
      title: 'Authorize Environmental Equilibrium',
      questionId: 'q4_grow_light_sync',
      requiredToCompleteStage: true,
      successEvent: 'STAGE_COMPLETED',
      feedbackMessage: 'Equilibrium code accepted! Grow lights engaged with vibrant glow. Facility exit opened.',
    },
  ],
  questions: [
    {
      id: 'q1_greenhouse_issue',
      prompt: 'Reviewing the multi-channel sensor telemetry table, which critical environmental parameter is failing safe crop thresholds?',
      type: 'multiple_choice',
      options: [
        'Soil moisture is critically low (31% vs 40% threshold)',
        'Temperature is freezing (< 10°C)',
        'Humidity is causing severe condensation (> 90%)',
        'Atmospheric pressure is dropping rapidly',
      ],
      correctAnswer: 'Soil moisture is critically low (31% vs 40% threshold)',
      explanation:
        'Soil moisture reads 31% volumetric water content, which falls well below the 40% threshold for active crop transpiration.',
      points: 100,
      maxAttempts: 3,
      stageId: 'stage-1',
      learningObjective: 'Interpret multi-channel agricultural IoT telemetry (moisture, lux, temp, RH)',
    },
    {
      id: 'q2_irrigation_action',
      prompt: 'With soil moisture at 31% and the safe root zone target set at 50%–70%, what actuator command must be dispatched to the manifold?',
      type: 'multiple_choice',
      options: [
        'ACTIVATE_IRRIGATION_PUMP',
        'PURGE_WATER_RESERVOIR',
        'DISABLE_SOIL_SENSORS',
        'DEACTIVATE_ALL_SOLENOIDS',
      ],
      correctAnswer: 'ACTIVATE_IRRIGATION_PUMP',
      explanation:
        'Engaging the automated drip irrigation pump starts water delivery through root drippers, replenishing soil hydration safely.',
      points: 100,
      maxAttempts: 3,
      stageId: 'stage-2',
      learningObjective: 'Identify soil moisture thresholds triggering automated drip irrigation',
    },
    {
      id: 'q3_ventilation_cooling',
      prompt: 'Canopy temperature has peaked at 29°C due to radiant heat gain. Which automated action should be engaged to bring temperatures toward 24°C?',
      type: 'multiple_choice',
      options: [
        'Turn ON ventilation exhaust fans',
        'Turn ON supplemental space heaters',
        'Seal all louvers and shut down air intake',
        'Drain the humidity reservoir',
      ],
      correctAnswer: 'Turn ON ventilation exhaust fans',
      explanation:
        'Ventilation exhaust fans evacuate trapped hot air and draw in fresh ambient air, initiating convective cooling across the plant canopy.',
      points: 100,
      maxAttempts: 3,
      stageId: 'stage-3',
      learningObjective: 'Calculate cooling airflow requirements for convective plant canopy regulation',
    },
    {
      id: 'q4_grow_light_sync',
      prompt: 'Enter the 7-character Climate Equilibrium Clearance Code revealed upon cooling the greenhouse to sync grow lights and unlock the exit:',
      type: 'code',
      correctAnswer: 'FLORA88',
      explanation: 'Code FLORA88 commits the photoperiod schedule and releases the botanical facility exit lock.',
      points: 200,
      maxAttempts: 5,
      stageId: 'stage-4',
      learningObjective: 'Execute automated environmental equilibrium sequences',
    },
  ],
  hints: [
    {
      id: 'hint-greenhouse-stage-1',
      stageId: 'stage-1',
      text: 'Examine the sensor telemetry: Soil moisture reads 31%, which is below the 40% safe threshold.',
      penalty: 15,
      order: 1,
    },
    {
      id: 'hint-greenhouse-stage-2',
      stageId: 'stage-2',
      text: 'To deliver water to the plants, select ACTIVATE_IRRIGATION_PUMP.',
      penalty: 15,
      order: 1,
    },
    {
      id: 'hint-greenhouse-stage-3',
      stageId: 'stage-3',
      text: 'To lower temperature from 29°C to 24°C, turn ON the ventilation exhaust fans.',
      penalty: 20,
      order: 1,
    },
    {
      id: 'hint-greenhouse-stage-4',
      stageId: 'stage-4',
      text: 'The equilibrium code was given in your Stage 3 intelligence clue: FLORA88.',
      penalty: 25,
      order: 1,
    },
  ],
  rewards: [
    {
      id: 'reward-greenhouse-stage-1-xp',
      type: 'XP',
      amount: 50,
    },
    {
      id: 'reward-greenhouse-stage-1-score',
      type: 'SCORE',
      amount: 100,
    },
    {
      id: 'reward-greenhouse-stage-2-xp',
      type: 'XP',
      amount: 50,
    },
    {
      id: 'reward-greenhouse-stage-2-score',
      type: 'SCORE',
      amount: 100,
    },
    {
      id: 'reward-greenhouse-stage-3-xp',
      type: 'XP',
      amount: 50,
    },
    {
      id: 'reward-greenhouse-stage-3-score',
      type: 'SCORE',
      amount: 100,
    },
    {
      id: 'reward-greenhouse-stage-3-clue-key',
      type: 'CLUE',
      value: 'Climate Equilibrium Key: FLORA88 (Target: 24°C, 62% Soil Moisture)',
    },
    {
      id: 'reward-greenhouse-stage-4-xp',
      type: 'XP',
      amount: 100,
    },
    {
      id: 'reward-greenhouse-stage-4-score',
      type: 'SCORE',
      amount: 200,
    },
    {
      id: 'reward-greenhouse-stage-4-badge-engineer',
      type: 'BADGE',
      badgeId: 'GREENHOUSE_ENGINEER',
      value: 'Greenhouse Engineer: Restored automated environmental homeostasis across closed plant canopies',
    },
  ],
  scene: {
    objects: [
      {
        id: 'plant_beds',
        name: 'Vegetative Crop Beds',
        type: 'ENVIRONMENT',
        position: [0.0, 0.4, -2.8],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-1',
        locked: false,
        visible: true,
        metadata: {
          cropType: 'Microgreens & Substrate Trays',
        },
      },
      {
        id: 'environmental_sensors',
        name: 'Multi-Spectral IoT Sensor Node',
        type: 'SENSOR',
        position: [-1.8, 1.4, -3.2],
        rotation: [0, 0.2, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-1',
        locked: false,
        visible: true,
        metadata: {
          sensors: 'Temp, Humidity, Soil Moisture, PAR Light',
        },
      },
      {
        id: 'irrigation_system',
        name: 'Automated Drip Irrigation Manifold',
        type: 'ACTUATOR',
        position: [1.8, 0.6, -3.2],
        rotation: [0, -0.2, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-2',
        locked: true,
        visible: true,
        metadata: {
          actuator: 'High-Pressure Drip Pump',
        },
      },
      {
        id: 'water_tank',
        name: 'Nutrient Water Storage Reservoir',
        type: 'EQUIPMENT',
        position: [3.2, 1.2, -4.0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-2',
        locked: true,
        visible: true,
        metadata: {
          capacity: '1000 Liters',
        },
      },
      {
        id: 'ventilation_fan',
        name: 'Greenhouse Gable Exhaust Fan',
        type: 'ACTUATOR',
        position: [0.0, 2.6, -4.8],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-3',
        locked: true,
        visible: true,
        metadata: {
          fanType: '3200 CFM Convective Air Mover',
        },
      },
      {
        id: 'grow_lights',
        name: 'Full-Spectrum Horticulture Grow Lights',
        type: 'ACTUATOR',
        position: [0.0, 2.8, -2.8],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-4',
        locked: true,
        visible: true,
        metadata: {
          spectrum: 'Full PAR (400-700nm)',
        },
      },
      {
        id: 'greenhouse_console',
        name: 'Master Greenhouse Climate Console',
        type: 'CONTROL_PANEL',
        position: [-3.5, 1.4, -1.8],
        rotation: [0, Math.PI / 3, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-4',
        locked: true,
        visible: true,
        metadata: {
          terminal: 'Automated Agro-Tech Core',
        },
      },
      {
        id: 'supply_cabinet',
        name: 'Agricultural Supplies Locker',
        type: 'CONTAINER',
        position: [-4.5, 1.5, 0.5],
        rotation: [0, Math.PI / 2, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-2',
        locked: true,
        visible: true,
        metadata: {
          contents: 'Soil calibration standards & nutrients',
        },
      },
      {
        id: 'exit_door',
        name: 'Botanical Facility Air-Lock Exit',
        type: 'EXIT_DOOR',
        position: [4.5, 1.5, 0.0],
        rotation: [0, -Math.PI / 2, 0],
        scale: [1, 1, 1],
        interactionType: 'INSPECT',
        stageId: 'stage-4',
        locked: true,
        visible: true,
        metadata: {
          lock: 'CLIMATE_EQUILIBRIUM_INTERLOCK',
        },
      },
    ],
  },
};
